# Generated by Django 4.2.13 on 2024-08-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Введите дату",
                null=True,
                verbose_name="Дата производства продукта",
            ),
        ),
    ]
